project/RestaurantManager/RestaurantManager/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from restaurant_home import urls as restaurant_home_urls
from restaurant_customer import urls as restaurant_customer_urls
from restaurant_employee import urls as restaurant_employee_urls
from restaurant_customer.api import OrderResource
from tastypie.api import Api

v1_api = Api(api_name='v1')
v1_api.register(OrderResource())

urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^accounts/', include('allauth.urls')),
	url(r'^customer/', include(restaurant_customer_urls)),
    url(r'^employee/', include(restaurant_employee_urls)),
    url(r'^sign-out/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name = 'sign-out' ),
    url(r'^api/', include(v1_api.urls)),
	url(r'^', include(restaurant_home_urls)),
]

project/RestaurantManager/restaurant_customer/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from restaurant_customer.views import OrderView

urlpatterns = [
	url(r'^$', OrderView.as_view(), name = 'order' ),
	
]

project/RestaurantManager/restaurant_employee/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from restaurant_employee.views import *
from django.contrib.admin.views.decorators import staff_member_required

urlpatterns = [
	url(r'^account/order-detail/(?P<pk>\d+)/', staff_member_required(UpdateOrderView.as_view()), name = 'order-detail' ),
	url(r'^account/', staff_member_required(AccountView.as_view()), name = 'account-employee' ),
	url(r'^$', SignInView.as_view(), name = 'sign-in-employee' ),
	
]

project/RestaurantManager/restaurant_home/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from restaurant_home.views import HomeView

urlpatterns = [
	url(r'^$', HomeView.as_view(), name = 'home' ),
	
]

project/RestaurantManager/restaurant_customer/models.py
from __future__ import unicode_literals

from django.db import models
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class FoodItem( models.Model ):
	id = models.AutoField( primary_key = True )
	name = models.CharField( max_length = 50, default = '' )
	description = models.CharField(max_length = 500, default = '')
	price = models.IntegerField()
	
	def __unicode__(self):
		separator = " - "
		return separator.join([self.name, self.description, str(self.price)])

class Order(models.Model):
	id = models.AutoField( primary_key = True )
	address = models.CharField(max_length = 250, default = '')
	details = models.CharField(max_length = 250, default = '')
	orderTime = models.DateTimeField()
	delivered = models.BooleanField(default = False)
	foodItems = models.ManyToManyField(FoodItem)
	user = models.ForeignKey(User)

project/RestaurantManager/restaurant_employee/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

project/RestaurantManager/restaurant_home/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

project/RestaurantManager/restaurant_customer/views.py
from django.shortcuts import render

from datetime import datetime, date, timedelta
from django.shortcuts import redirect
from django.views.generic import *
from form import *
# Create your views here.


class OrderView(FormView):
	template_name = 'restaurant_customer/order.html'
	form_class = OrderForm
	success_message = ('Comanda a fost realizata cu succes.')
	success_url = '/'

	def dispatch(self, request, *args, **kwargs):

		if not request.user.is_authenticated():
			return redirect( 'home' )

		return super( OrderView, self ).dispatch( request, *args, **kwargs )

	def post( self, request, *args, **kwargs ):
		form = self.get_form()

		if form.is_valid():
			order = Order()
			order.orderTime = datetime.now() + timedelta( hours = 1 )
			order.adrress = form.cleaned_data['address']
			order.details = form.cleaned_data['details']
			order.user_id = request.user.pk
			order.save()

			items_ids = [item.pk for item in form.cleaned_data['foodItems']]
			items = FoodItem.objects.filter(pk__in = items_ids)

			for item in items:
				order.foodItems.add(item)
			

		return super( OrderView, self ).post( self, request, *args, **kwargs )

project/RestaurantManager/restaurant_employee/views.py
from django.shortcuts import render

from django.views.generic import *
from django.core.urlresolvers import reverse, reverse_lazy
from django.shortcuts import redirect

from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login

from restaurant_customer.models import Order
from form import *
# Create your views here.


class SignInView( FormView ):
	template_name = 'restaurant_employee/sign-in.html'
	form_class = SignInForm
	success_url = reverse_lazy('account-employee')

	def dispatch(self, request, *args, **kwargs):

		if request.user.is_authenticated():
			return redirect( 'account-employee' )

		return super( SignInView, self ).dispatch( request, *args, **kwargs )

	def post( self, request, *args, **kwargs ):

		form = self.get_form()

		if( form.is_valid() ):
			if form.get_user() is not None:
				login( request, form.get_user() )

		return super( SignInView, self ).post( self, request, *args, **kwargs )



class AccountView(ListView):
	template_name = 'restaurant_employee/orderlist.html'
	model = Order


class UpdateOrderView(UpdateView):
	template_name = 'restaurant_employee/update-order.html'
	form_class = UpdateOrderForm
	success_url = reverse_lazy('account-employee')

	def get_object( self, queryset = None ):
		try:
			return Order.objects.get( pk = self.kwargs['pk'])
		except Order.DoesNotExist:
			raise Http404

project/RestaurantManager/restaurant_home/views.py
from django.shortcuts import render

from django.shortcuts import redirect
from django.views.generic import TemplateView
# Create your views here.


class HomeView(TemplateView):
	template_name = 'index.html'
	
	def dispatch(self, request, *args, **kwargs):
		if self.request.user.is_authenticated():
			if self.request.user.is_superuser:
				return redirect( 'admin:index' )
			return redirect( 'order' )
		
		return super( HomeView, self).dispatch( request, *args, **kwargs )

project/RestaurantManager/restaurant_customer/templates/restaurant_customer/order.html
{% load i18n %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" type="text/css" href="{% static 'restaurant_home/bootstrap/css/bootstrap.min.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'restaurant_home/css/style.css' %}" />
		<script type="text/javascript" src="{% static 'restaurant_home/js/jquery/jquery.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'restaurant_home/bootstrap/js/bootstrap.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'restaurant_home/js/support.js' %}"></script>
		<script src="https://maps.googleapis.com/maps/api/js"></script>
		<title>{% trans "Brb Restaurant" %}</title>
	</head>
	<body>
		<div class="container">
			<div class="container-fluid">
				<div class="row text-right">
					<form method="get" action="{% url 'sign-out' %}">
						<button type="submit">{% trans "Ieșire" %}</button>
					</form>
				</div>
			</div>
		</div>
		<div class="container" id="about">
			<div class="container-fluid">
				<h1 class="text-center" >{% trans 'Despre noi'%}</h1>
				<div class="col-md-8">
					<div class="center-block">
					<p>Strada George Barițiu 28, Cluj-Napoca 400000, România:<br>
						Tel: +39 373 527 91 27<br>
						E-mail: brbrestaurant@gmail.com
					</p>
				</div>
				</div>
				<div class="col-md-4">
					<div id="map"></div>
				</div>
			</div>
		</div>
		<div class="container">
			<div class="container-fluid">
				<div class="row">
					<form action="" method="post">{% csrf_token %}
						
							<div class="form-group{% if field.errors %} has-error{% endif %}{% if field.field.required %} field-required{% endif %}">
							{% for field in form %}
								{% ifequal field.label|lower 'fooditems' %}
									{% for item in field %}
										<div class="row" id="form-row">
											{{item}} RON
										</div>
									{% endfor %}
								{% else %}
								<label class="control-label" for="id_{{ field.name }}">
									{{ field.label }}:
								</label>
									{{field}}
								{% endifequal %}
							{% endfor %}
							</div>
						
						<button type="submit" class="btn btn-primary">{%  trans "Trimite comanda" %}</button>
					</form>
				</div>
			</div>

		</div>


		
	</body>
</html>

project/RestaurantManager/restaurant_employee/templates/restaurant_employee/orderlist.html
{% load staticfiles %}
{% load i18n %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" type="text/css" href="{% static 'restaurant_home/bootstrap/css/bootstrap.min.css' %}" />
		<script type="text/javascript" src="{% static 'restaurant_home/js/jquery/jquery.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'restaurant_home/bootstrap/js/bootstrap.min.js' %}"></script>
		<title>{% trans "Order List" %}</title>
	</head>
	<body>
		<div class="container">
			<div class="container-fluid">
				<div class="row text-right">
					<form method="get" action="{% url 'sign-out' %}">
						<button type="submit">{% trans "Ieșire" %}</button>
					</form>
				</div>
			</div>
		</div>
		<div class="container-fluid">
			<div class="row">
                <div id="left-content" class="col-xs-12 col-sm-2 col-md-2 col-lg-2">
                </div>
                <div class="col-xs-offset-0 col-xs-12 col-sm-offset-2 col-sm-10 col-md-offset-2 col-md-10 col-lg-offset-2 col-lg-10">
    				<div  id="main-content" class="col-xs-12 col-sm-12 col-md-12 col-lg-9">
						<hr>
						<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
							{% for order in object_list %}
								<div class="panel panel-default">
									<div class="panel-heading panel-collapsible collapsed" role="tab" id="heading{{ forloop.counter }}" data-toggle="collapse" data-parent="#accordion" href="#collapse{{ forloop.counter }}" style="color:{% if order.delivered %}blue{% else %}red{% endif %};">
										<h3>
											{{ order.orderTime }}
										</h3>
									</div>
									<div id="collapse{{ forloop.counter }}" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading{{ forloop.counter }}">
										<div class="panel-body">
											<h4>
												<a class="btn btn-default" href="{% url 'order-detail' pk=order.pk %}"><i class="fa fa-edit"></i> {% trans 'Modifica comanda' %}</a>
											</h4>
											<hr>
											<div id="details" class="panel-body-pad">
												<p>{% trans "id: " %}{{order.id}}</p> 
												<p>{% trans "adresa: " %}{{order.address}}</p>
												<p>{% trans "detalii: " %}{{order.details}}</p>
												<p>{% trans "livrata: " %}{{order.delivered}}</p>
											</div>
										</div>
									</div>
								</div>

							{% empty %}
								{% trans "Nu ai încă nici o comanda." %}
							{% endfor %}
						</div>
						</div>
    				</div>
                </div>
				<div  id="side-content" class="col-sm-3 side-col">
				</div>
			</div>
		</div>
	</body>
</html>

project/RestaurantManager/restaurant_employee/templates/restaurant_employee/sign-in.html
{% load staticfiles %}
{% load i18n %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" type="text/css" href="{% static 'restaurant_home/bootstrap/css/bootstrap.min.css' %}" />
		<script type="text/javascript" src="{% static 'restaurant_home/js/jquery/jquery.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'restaurant_home/bootstrap/js/bootstrap.min.js' %}"></script>
		<title>{% trans "Autentificare" %}</title>
	</head>
	<body>
		<div class="container-fluid">
			<div class="row">
				<div class="col-xs-12 col-sm-offset-2 col-sm-8 col-md-offset-4 col-md-5 col-lg-offset-4 col-lg-4">
					<h1 class="text-center">{% trans "Autentificare" %}</h1>
					<div class="centerbox box-shadow--2dp">
						<form action="" method="post">
							{% csrf_token %}
							{% for field in form %}
								{% if field.name in fields_to_show or not fields_to_show %}
								<div class="form-group{% if field.errors %} has-error{% endif %}{% if field.field.required %} field-required{% endif %}">
									<label class="control-label" for="id_{{ field.name }}">
										{{ field.label }}:
									</label>
									<div class="alert-danger">{{ field.errors|striptags }}</div>
									{{ field }}
									<div class="text-muted"><small>{{ field.help_text }}</small></div>
								</div>
								{% endif %}
							{% endfor %}
							<div class="row">
								<div class="col-md-6">
									<label for="remember" data-toggle="tooltip" title="Timp de {{ request.session.get_expiry_date|timeuntil }}. Dacă deselectezi, sesiunea ta expiră atunci când închizi browser-ul.">
									</label>
								</div>
								<div class="col-md-6 text-right">
									<button type="submit" class="btn btn-primary">{% trans "Autentificare" %}</button>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</body>
</html>

project/RestaurantManager/restaurant_employee/templates/restaurant_employee/update-order.html
{% load staticfiles %}
{% load i18n %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" type="text/css" href="{% static 'restaurant_home/bootstrap/css/bootstrap.min.css' %}" />
		<script src="http://code.jquery.com/jquery-2.1.4.min.js"></script>
		<script type="text/javascript" src="{% static 'restaurant_home/bootstrap/js/bootstrap.min.js' %}"></script>
		<title>{% trans "Brb Restaurant" %}</title>
	</head>
	<body>
		<div class="container-fluid">
			<div class="row">
				<div class="col-xs-12 col-sm-offset-2 col-sm-8 col-md-offset-4 col-md-5 col-lg-offset-4 col-lg-4">
					<div class="centerbox box-shadow--2dp">
						<form action="" method="put">
							{% csrf_token %}
							{% for field in form %}
								{% if field.name in fields_to_show or not fields_to_show %}
								<div class="form-group{% if field.errors %} has-error{% endif %}{% if field.field.required %} field-required{% endif %}">
									<label class="control-label" for="id_{{ field.name }}">
										{{ field.label }}:
									</label>
									<div class="alert-danger">{{ field.errors|striptags }}</div>
									{{ field }}
									<div class="text-muted"><small>{{ field.help_text }}</small></div>
								</div>
								{% endif %}
							{% endfor %}
							<div id="id_object" class="hidden">
								<p>{{object.pk}}</p>
							</div>
							<div class="row">
								<div class="col-md-6">
									<label for="remember" data-toggle="tooltip" title="Timp de {{ request.session.get_expiry_date|timeuntil }}. Dacă deselectezi, sesiunea ta expiră atunci când închizi browser-ul.">
									</label>
								</div>
								<div class="col-md-6 text-right">
									<button id="submit" type="submit" class="btn btn-primary">{% trans "Modifica" %}</button>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>

		<script>
			//When submit is clicked
			 $("#submit").click(function(e) {
			//Prevent default submit. Must for Ajax post.Beginner's pit.
			 e.preventDefault();

			//Collect data from fields
			 var delivered = $('#id_delivered').is(':checked') ? true: false;
			 var id_object = $('#id_object p').text();

			//This is the Ajax post.Observe carefully. It is nothing but details of where_to_post,what_to_post
			//Send data  
			 $.ajax({
			       url : "http://192.168.33.10:8000/api/v1/order/" + id_object + "/", // the endpoint,commonly same url
			       type : "PUT", // http method
			       dataType: "application/json",
			       contentType: "application/json",
			       data : JSON.stringify({
			       						 "delivered": delivered
			       						}), // data sent with the put request
			 });

			 
			});
		</script>

	</body>
</html>

project/RestaurantManager/restaurant_home/templates/index.html
{% load i18n %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" type="text/css" href="{% static 'restaurant_home/bootstrap/css/bootstrap.min.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'restaurant_home/css/style.css' %}" />
		<script type="text/javascript" src="{% static 'restaurant_home/js/jquery/jquery.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'restaurant_home/bootstrap/js/bootstrap.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'restaurant_home/js/support.js' %}"></script>
		<script src="https://maps.googleapis.com/maps/api/js"></script>
		<title>{% trans "Brb Restaurant" %}</title>
	</head>
	<body>
		<div class="container">
			<div class="row">
				<div id="menu">
					{% load socialaccount %}
					{% providers_media_js %}
					{% csrf_token %}
					<a href="{% provider_login_url "facebook" method="js_sdk" next='/customer' %}">Facebook Connect</a>

				</div>
			</div>
		</div>
		<div class="container-fluid">
			<div class="row">
				<div id="jumbotron">
					<div class="container-fluid">
						<div class="row">
							<div id="home-main">
								<div class="col-lg-12">
									<div class="col-md-8 col-lg-7">
										<h1>{% trans "Iti este foame?" %}</h1>
										<h4>
											{% blocktrans %}
											Comanda ceva de mancare
											{% endblocktrans %}
										</h4>
										{% load socialaccount %}
										{% providers_media_js %}
										{% csrf_token %}
										<a class="btn btn-default" href="{% provider_login_url "facebook" method="js_sdk" next='/customer' %}">{% trans 'Du-ma la meniu' %}</a>
										<div class="vert-spacer"></div>
									</div>
								</div>
							</div>
						</div>
						<div class="container-fluid">
							<div class="row vert-spacer">
								<div class="col-md-8 col-md-offset-2">
									<h1 class="text-right" id="main-text">{% trans 'Brb Restaurant'%}</h1>
									<div class="text-center vert-spacer">
										
									</div>
								</div>
							</div>
							<hr>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="container" id="about">
			<div class="container-fluid">
				<h1 class="text-center" >{% trans 'Despre noi'%}</h1>
				  <div class="col-md-8">
				  	<div class="center-block">
						<p>Strada George Barițiu 28, Cluj-Napoca 400000, România:<br>
							Tel: +39 373 527 91 27<br>
							E-mail: brbrestaurant@gmail.com
						</p>
					</div>
				  </div>
				  <div class="col-md-4">
				  	<div id="map"></div>
				  </div>
					
				</div>
		</div>

		
	</body>
</html>